export const API_ENDPOINTS = {
  login: "/api/auth/login",
  register: "/api/auth/register",
  logout: "/api/auth/logout",
  forgotPassword: "/api/auth/forgot-password",
  registerOtpSend: "/api/auth/register/otp/send",
  registerOtpVerify: "/api/auth/register/otp/verify",
  transcripts: "/api/transcripts",
  transcriptDetail: "/api/transcripts/:id",
  transcriptFullText: "/api/transcripts/:id/full-text",
  transcriptDownload: "/api/transcripts/:id/download",
  domains: "/api/domains",
  saved: "/api/saved",
  cart: "/api/cart",
  checkout: "/api/checkout",
  checkoutIntent: "/api/checkout/intent",
  orders: "/api/orders",
  orderVerify: "/api/orders/verify",
  orderDetail: "/api/orders/:id",
  orderReceipt: "/api/orders/:id/receipt",
  profile: "/api/users/me",
  topicsRequest: "/api/topics/request",
  support: "/api/support",
} as const;
